name: Python CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
#   release:
#     types: [created]

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools

      - name: Install ffmpeg (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          choco install ffmpeg

      - name: Install ffmpeg (MacOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          choco install ffmpeg
          
      - name: Install ffmpeg (Linux)
        if: ${{ matrix.os == 'linux-latest' }}
        run: |
          sudo apt-get install ffmpeg
          
      - name: Test
        run: |
          python setup.py test

      - name: Build
        run: |
          python setup.py install
